### ISSUE TITLE
Broken link to resource downloads

### ISSUE THREAD

**Issue by jleung51** [nstbayless/sdlgame#2]
The [`src/` README](https://github.com/nstbayless/sdlgame/blob/1e7469cd518b01ea49ed09f194d67179d85ac804/src/README.md) and the [`resources/` README](https://github.com/nstbayless/sdlgame/blob/1e7469cd518b01ea49ed09f194d67179d85ac804/resources/README.md) link to the old Bitbucket resource downloads, which are no longer available.

**Comment by nstbayless** [comment]
yeaahahhhhh....
